title: "RCL CloudTnT"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
  "RCL CloudTnT Docs on GitHub":
    - "https://github.com/cloudtnt-rcl/docs"
callouts:
  information:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red