title: RCL CloudTnT
description: Digital transformation hub for individuals and small business.
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

url: https://rcl-cloudtnt.github.io/docs

aux_links:
  Edit on GitHub: https://github.com/rcl-cloudtnt/docs

callouts:
  information:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red